[package]
name = "rush"
version = "0.1.0"
edition = "2021"


[dependencies]
crossterm = "0.26.1"
clap = {version = "4.1.8", features = ["derive"]}
text-colorizer = "1"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1